// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/operator/v1/users.proto

package operatorv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "hmans.de/chatto/internal/pb/chatto/admin/v1"
	v11 "hmans.de/chatto/internal/pb/chatto/api/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a user as a local operator action.
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required login for the new user.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Optional display name. Defaults to login when empty.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional password. When present, it must satisfy server password policy.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Optional email to add as already verified.
	VerifiedEmail string `protobuf:"bytes,4,opt,name=verified_email,json=verifiedEmail,proto3" json:"verified_email,omitempty"`
	// Optional explicit roles to assign after creation.
	RoleNames     []string `protobuf:"bytes,5,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetVerifiedEmail() string {
	if x != nil {
		return x.VerifiedEmail
	}
	return ""
}

func (x *CreateUserRequest) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

// Result of creating a user.
type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created member row.
	Member        *v1.AdminMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request operator-visible user rows.
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Case-insensitive login/display-name search term. Empty disables search.
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// Page request. Defaults to 20 results when absent or limit is zero.
	Page          *v11.PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Operator-visible user rows plus role summaries.
type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching users.
	Users []*v1.AdminMember `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Roles for display-name lookup.
	Roles []*v1.AdminRoleReference `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Page metadata.
	Page          *v11.PageInfo `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*v1.AdminMember {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetRoles() []*v1.AdminRoleReference {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *v11.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Request one operator-visible user detail record.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Target login. Provide exactly one lookup field.
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// Target verified email address. Provide exactly one lookup field.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Operator-visible user detail payload.
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Member record.
	Member *v1.AdminMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// Roles for assignment.
	Roles []*v1.AdminMemberRole `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// Permissions available for per-user overrides.
	AvailablePermissions []string `protobuf:"bytes,3,rep,name=available_permissions,json=availablePermissions,proto3" json:"available_permissions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GetUserResponse) GetRoles() []*v1.AdminMemberRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserResponse) GetAvailablePermissions() []string {
	if x != nil {
		return x.AvailablePermissions
	}
	return nil
}

// Request to assign a role to a user.
type AssignRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Role name to assign.
	RoleName      string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{6}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// Result of assigning a role.
type AssignRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Assigned bool `protobuf:"varint,1,opt,name=assigned,proto3" json:"assigned,omitempty"`
	// Updated member row.
	Member        *v1.AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{7}
}

func (x *AssignRoleResponse) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

func (x *AssignRoleResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to revoke a role from a user.
type RevokeRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Role name to revoke.
	RoleName      string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// Result of revoking a role.
type RevokeRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Revoked bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// Updated member row.
	Member        *v1.AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeRoleResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeRoleResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to update a user's identity as an operator action.
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New display name, when changing it.
	DisplayName *string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// New login identifier, when changing it.
	Login         *string `protobuf:"bytes,3,opt,name=login,proto3,oneof" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetLogin() string {
	if x != nil && x.Login != nil {
		return *x.Login
	}
	return ""
}

// Result of an operator user update.
type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated user profile.
	User *v11.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Updated member row.
	Member        *v1.AdminMember `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserResponse) GetUser() *v11.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to set a user's password as an operator action.
type SetUserPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordRequest) Reset() {
	*x = SetUserPasswordRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordRequest) ProtoMessage() {}

func (x *SetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Result of setting a user's password.
type SetUserPasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated member row.
	Member        *v1.AdminMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserPasswordResponse) Reset() {
	*x = SetUserPasswordResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPasswordResponse) ProtoMessage() {}

func (x *SetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserPasswordResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to permanently delete a user account.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Result of deleting a user account.
type DeleteUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the account was deleted.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Request to add a verified email address to a user.
type AddVerifiedEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Email address to mark as verified.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVerifiedEmailRequest) Reset() {
	*x = AddVerifiedEmailRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVerifiedEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVerifiedEmailRequest) ProtoMessage() {}

func (x *AddVerifiedEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVerifiedEmailRequest.ProtoReflect.Descriptor instead.
func (*AddVerifiedEmailRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{16}
}

func (x *AddVerifiedEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddVerifiedEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Result of adding a verified email address.
type AddVerifiedEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated member row.
	Member        *v1.AdminMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVerifiedEmailResponse) Reset() {
	*x = AddVerifiedEmailResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVerifiedEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVerifiedEmailResponse) ProtoMessage() {}

func (x *AddVerifiedEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVerifiedEmailResponse.ProtoReflect.Descriptor instead.
func (*AddVerifiedEmailResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{17}
}

func (x *AddVerifiedEmailResponse) GetMember() *v1.AdminMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to clear a user's self-service username-change cooldown.
type ClearUsernameCooldownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user ID.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUsernameCooldownRequest) Reset() {
	*x = ClearUsernameCooldownRequest{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUsernameCooldownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUsernameCooldownRequest) ProtoMessage() {}

func (x *ClearUsernameCooldownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUsernameCooldownRequest.ProtoReflect.Descriptor instead.
func (*ClearUsernameCooldownRequest) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{18}
}

func (x *ClearUsernameCooldownRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Result of clearing a user's username-change cooldown.
type ClearUsernameCooldownResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Cleared       bool `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUsernameCooldownResponse) Reset() {
	*x = ClearUsernameCooldownResponse{}
	mi := &file_chatto_operator_v1_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUsernameCooldownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUsernameCooldownResponse) ProtoMessage() {}

func (x *ClearUsernameCooldownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_operator_v1_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUsernameCooldownResponse.ProtoReflect.Descriptor instead.
func (*ClearUsernameCooldownResponse) Descriptor() ([]byte, []int) {
	return file_chatto_operator_v1_users_proto_rawDescGZIP(), []int{19}
}

func (x *ClearUsernameCooldownResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

var File_chatto_operator_v1_users_proto protoreflect.FileDescriptor

const file_chatto_operator_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1echatto/operator/v1/users.proto\x12\x12chatto.operator.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1dchatto/admin/v1/members.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x19chatto/api/v1/users.proto\"\xe0\x01\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\x05login\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x05login\x12*\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18PR\vdisplayName\x12$\n" +
	"\bpassword\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\bpassword\x12/\n" +
	"\x0everified_email\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xc0\x02R\rverifiedEmail\x12'\n" +
	"\n" +
	"role_names\x18\x05 \x03(\tB\b\xbaH\x05\x92\x01\x02\x10\x14R\troleNames\"J\n" +
	"\x12CreateUserResponse\x124\n" +
	"\x06member\x18\x01 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"Z\n" +
	"\x10ListUsersRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"\xaf\x01\n" +
	"\x11ListUsersResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.chatto.admin.v1.AdminMemberR\x05users\x129\n" +
	"\x05roles\x18\x02 \x03(\v2#.chatto.admin.v1.AdminRoleReferenceR\x05roles\x12+\n" +
	"\x04page\x18\x03 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\"U\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xb4\x01\n" +
	"\x0fGetUserResponse\x124\n" +
	"\x06member\x18\x01 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\x126\n" +
	"\x05roles\x18\x02 \x03(\v2 .chatto.admin.v1.AdminMemberRoleR\x05roles\x123\n" +
	"\x15available_permissions\x18\x03 \x03(\tR\x14availablePermissions\"[\n" +
	"\x11AssignRoleRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\trole_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\broleName\"f\n" +
	"\x12AssignRoleResponse\x12\x1a\n" +
	"\bassigned\x18\x01 \x01(\bR\bassigned\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"[\n" +
	"\x11RevokeRoleRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12$\n" +
	"\trole_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\broleName\"d\n" +
	"\x12RevokeRoleResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"\x93\x01\n" +
	"\x11UpdateUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x19\n" +
	"\x05login\x18\x03 \x01(\tH\x01R\x05login\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\b\n" +
	"\x06_login\"s\n" +
	"\x12UpdateUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.chatto.api.v1.UserR\x04user\x124\n" +
	"\x06member\x18\x02 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"b\n" +
	"\x16SetUserPasswordRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\bpassword\"O\n" +
	"\x17SetUserPasswordResponse\x124\n" +
	"\x06member\x18\x01 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"5\n" +
	"\x11DeleteUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"]\n" +
	"\x17AddVerifiedEmailRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xc0\x02R\x05email\"P\n" +
	"\x18AddVerifiedEmailResponse\x124\n" +
	"\x06member\x18\x01 \x01(\v2\x1c.chatto.admin.v1.AdminMemberR\x06member\"@\n" +
	"\x1cClearUsernameCooldownRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"9\n" +
	"\x1dClearUsernameCooldownResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared2\xed\a\n" +
	"\x13OperatorUserService\x12[\n" +
	"\n" +
	"CreateUser\x12%.chatto.operator.v1.CreateUserRequest\x1a&.chatto.operator.v1.CreateUserResponse\x12X\n" +
	"\tListUsers\x12$.chatto.operator.v1.ListUsersRequest\x1a%.chatto.operator.v1.ListUsersResponse\x12R\n" +
	"\aGetUser\x12\".chatto.operator.v1.GetUserRequest\x1a#.chatto.operator.v1.GetUserResponse\x12[\n" +
	"\n" +
	"AssignRole\x12%.chatto.operator.v1.AssignRoleRequest\x1a&.chatto.operator.v1.AssignRoleResponse\x12[\n" +
	"\n" +
	"RevokeRole\x12%.chatto.operator.v1.RevokeRoleRequest\x1a&.chatto.operator.v1.RevokeRoleResponse\x12[\n" +
	"\n" +
	"UpdateUser\x12%.chatto.operator.v1.UpdateUserRequest\x1a&.chatto.operator.v1.UpdateUserResponse\x12j\n" +
	"\x0fSetUserPassword\x12*.chatto.operator.v1.SetUserPasswordRequest\x1a+.chatto.operator.v1.SetUserPasswordResponse\x12[\n" +
	"\n" +
	"DeleteUser\x12%.chatto.operator.v1.DeleteUserRequest\x1a&.chatto.operator.v1.DeleteUserResponse\x12m\n" +
	"\x10AddVerifiedEmail\x12+.chatto.operator.v1.AddVerifiedEmailRequest\x1a,.chatto.operator.v1.AddVerifiedEmailResponse\x12|\n" +
	"\x15ClearUsernameCooldown\x120.chatto.operator.v1.ClearUsernameCooldownRequest\x1a1.chatto.operator.v1.ClearUsernameCooldownResponseB\xc9\x01\n" +
	"\x16com.chatto.operator.v1B\n" +
	"UsersProtoP\x01Z9hmans.de/chatto/internal/pb/chatto/operator/v1;operatorv1\xa2\x02\x03COX\xaa\x02\x12Chatto.Operator.V1\xca\x02\x12Chatto\\Operator\\V1\xe2\x02\x1eChatto\\Operator\\V1\\GPBMetadata\xea\x02\x14Chatto::Operator::V1b\x06proto3"

var (
	file_chatto_operator_v1_users_proto_rawDescOnce sync.Once
	file_chatto_operator_v1_users_proto_rawDescData []byte
)

func file_chatto_operator_v1_users_proto_rawDescGZIP() []byte {
	file_chatto_operator_v1_users_proto_rawDescOnce.Do(func() {
		file_chatto_operator_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_operator_v1_users_proto_rawDesc), len(file_chatto_operator_v1_users_proto_rawDesc)))
	})
	return file_chatto_operator_v1_users_proto_rawDescData
}

var file_chatto_operator_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_chatto_operator_v1_users_proto_goTypes = []any{
	(*CreateUserRequest)(nil),             // 0: chatto.operator.v1.CreateUserRequest
	(*CreateUserResponse)(nil),            // 1: chatto.operator.v1.CreateUserResponse
	(*ListUsersRequest)(nil),              // 2: chatto.operator.v1.ListUsersRequest
	(*ListUsersResponse)(nil),             // 3: chatto.operator.v1.ListUsersResponse
	(*GetUserRequest)(nil),                // 4: chatto.operator.v1.GetUserRequest
	(*GetUserResponse)(nil),               // 5: chatto.operator.v1.GetUserResponse
	(*AssignRoleRequest)(nil),             // 6: chatto.operator.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),            // 7: chatto.operator.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),             // 8: chatto.operator.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),            // 9: chatto.operator.v1.RevokeRoleResponse
	(*UpdateUserRequest)(nil),             // 10: chatto.operator.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 11: chatto.operator.v1.UpdateUserResponse
	(*SetUserPasswordRequest)(nil),        // 12: chatto.operator.v1.SetUserPasswordRequest
	(*SetUserPasswordResponse)(nil),       // 13: chatto.operator.v1.SetUserPasswordResponse
	(*DeleteUserRequest)(nil),             // 14: chatto.operator.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 15: chatto.operator.v1.DeleteUserResponse
	(*AddVerifiedEmailRequest)(nil),       // 16: chatto.operator.v1.AddVerifiedEmailRequest
	(*AddVerifiedEmailResponse)(nil),      // 17: chatto.operator.v1.AddVerifiedEmailResponse
	(*ClearUsernameCooldownRequest)(nil),  // 18: chatto.operator.v1.ClearUsernameCooldownRequest
	(*ClearUsernameCooldownResponse)(nil), // 19: chatto.operator.v1.ClearUsernameCooldownResponse
	(*v1.AdminMember)(nil),                // 20: chatto.admin.v1.AdminMember
	(*v11.PageRequest)(nil),               // 21: chatto.api.v1.PageRequest
	(*v1.AdminRoleReference)(nil),         // 22: chatto.admin.v1.AdminRoleReference
	(*v11.PageInfo)(nil),                  // 23: chatto.api.v1.PageInfo
	(*v1.AdminMemberRole)(nil),            // 24: chatto.admin.v1.AdminMemberRole
	(*v11.User)(nil),                      // 25: chatto.api.v1.User
}
var file_chatto_operator_v1_users_proto_depIdxs = []int32{
	20, // 0: chatto.operator.v1.CreateUserResponse.member:type_name -> chatto.admin.v1.AdminMember
	21, // 1: chatto.operator.v1.ListUsersRequest.page:type_name -> chatto.api.v1.PageRequest
	20, // 2: chatto.operator.v1.ListUsersResponse.users:type_name -> chatto.admin.v1.AdminMember
	22, // 3: chatto.operator.v1.ListUsersResponse.roles:type_name -> chatto.admin.v1.AdminRoleReference
	23, // 4: chatto.operator.v1.ListUsersResponse.page:type_name -> chatto.api.v1.PageInfo
	20, // 5: chatto.operator.v1.GetUserResponse.member:type_name -> chatto.admin.v1.AdminMember
	24, // 6: chatto.operator.v1.GetUserResponse.roles:type_name -> chatto.admin.v1.AdminMemberRole
	20, // 7: chatto.operator.v1.AssignRoleResponse.member:type_name -> chatto.admin.v1.AdminMember
	20, // 8: chatto.operator.v1.RevokeRoleResponse.member:type_name -> chatto.admin.v1.AdminMember
	25, // 9: chatto.operator.v1.UpdateUserResponse.user:type_name -> chatto.api.v1.User
	20, // 10: chatto.operator.v1.UpdateUserResponse.member:type_name -> chatto.admin.v1.AdminMember
	20, // 11: chatto.operator.v1.SetUserPasswordResponse.member:type_name -> chatto.admin.v1.AdminMember
	20, // 12: chatto.operator.v1.AddVerifiedEmailResponse.member:type_name -> chatto.admin.v1.AdminMember
	0,  // 13: chatto.operator.v1.OperatorUserService.CreateUser:input_type -> chatto.operator.v1.CreateUserRequest
	2,  // 14: chatto.operator.v1.OperatorUserService.ListUsers:input_type -> chatto.operator.v1.ListUsersRequest
	4,  // 15: chatto.operator.v1.OperatorUserService.GetUser:input_type -> chatto.operator.v1.GetUserRequest
	6,  // 16: chatto.operator.v1.OperatorUserService.AssignRole:input_type -> chatto.operator.v1.AssignRoleRequest
	8,  // 17: chatto.operator.v1.OperatorUserService.RevokeRole:input_type -> chatto.operator.v1.RevokeRoleRequest
	10, // 18: chatto.operator.v1.OperatorUserService.UpdateUser:input_type -> chatto.operator.v1.UpdateUserRequest
	12, // 19: chatto.operator.v1.OperatorUserService.SetUserPassword:input_type -> chatto.operator.v1.SetUserPasswordRequest
	14, // 20: chatto.operator.v1.OperatorUserService.DeleteUser:input_type -> chatto.operator.v1.DeleteUserRequest
	16, // 21: chatto.operator.v1.OperatorUserService.AddVerifiedEmail:input_type -> chatto.operator.v1.AddVerifiedEmailRequest
	18, // 22: chatto.operator.v1.OperatorUserService.ClearUsernameCooldown:input_type -> chatto.operator.v1.ClearUsernameCooldownRequest
	1,  // 23: chatto.operator.v1.OperatorUserService.CreateUser:output_type -> chatto.operator.v1.CreateUserResponse
	3,  // 24: chatto.operator.v1.OperatorUserService.ListUsers:output_type -> chatto.operator.v1.ListUsersResponse
	5,  // 25: chatto.operator.v1.OperatorUserService.GetUser:output_type -> chatto.operator.v1.GetUserResponse
	7,  // 26: chatto.operator.v1.OperatorUserService.AssignRole:output_type -> chatto.operator.v1.AssignRoleResponse
	9,  // 27: chatto.operator.v1.OperatorUserService.RevokeRole:output_type -> chatto.operator.v1.RevokeRoleResponse
	11, // 28: chatto.operator.v1.OperatorUserService.UpdateUser:output_type -> chatto.operator.v1.UpdateUserResponse
	13, // 29: chatto.operator.v1.OperatorUserService.SetUserPassword:output_type -> chatto.operator.v1.SetUserPasswordResponse
	15, // 30: chatto.operator.v1.OperatorUserService.DeleteUser:output_type -> chatto.operator.v1.DeleteUserResponse
	17, // 31: chatto.operator.v1.OperatorUserService.AddVerifiedEmail:output_type -> chatto.operator.v1.AddVerifiedEmailResponse
	19, // 32: chatto.operator.v1.OperatorUserService.ClearUsernameCooldown:output_type -> chatto.operator.v1.ClearUsernameCooldownResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_chatto_operator_v1_users_proto_init() }
func file_chatto_operator_v1_users_proto_init() {
	if File_chatto_operator_v1_users_proto != nil {
		return
	}
	file_chatto_operator_v1_users_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_operator_v1_users_proto_rawDesc), len(file_chatto_operator_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_operator_v1_users_proto_goTypes,
		DependencyIndexes: file_chatto_operator_v1_users_proto_depIdxs,
		MessageInfos:      file_chatto_operator_v1_users_proto_msgTypes,
	}.Build()
	File_chatto_operator_v1_users_proto = out.File
	file_chatto_operator_v1_users_proto_goTypes = nil
	file_chatto_operator_v1_users_proto_depIdxs = nil
}
