// Code generated by tygo. DO NOT EDIT.

//////////
// source: permission.go

/**
 * PermissionScope marks where a permission can be configured.
 * Most permissions apply at the server level (default). Channel-room
 * permissions (e.g. message.post) additionally include ScopeGroup (to be
 * configured per room group) and ScopeRoom (to be overridden per individual
 * room).
 */
export type PermissionScope = string;
export const ScopeServer: PermissionScope = "server";
export const ScopeGroup: PermissionScope = "group";
export const ScopeRoom: PermissionScope = "room";
/**
 * PermissionCategory groups related permissions for UI organization.
 */
export type PermissionCategory = string;
export const CategoryServer: PermissionCategory = "server";
export const CategoryRoom: PermissionCategory = "room";
export const CategoryMessage: PermissionCategory = "message";
export const CategoryRole: PermissionCategory = "role";
export const CategoryAdmin: PermissionCategory = "admin";
export const CategoryDM: PermissionCategory = "dm";
export const CategoryUser: PermissionCategory = "user";
/**
 * Permission represents a permission in the permission model.
 */
export type Permission = string;
/**
 * PermServerManage allows updating server settings (name, description, logo).
 */
export const PermServerManage: Permission = "server.manage";
/**
 * PermRoomCreate allows creating new rooms.
 */
export const PermRoomCreate: Permission = "room.create";
/**
 * PermRoomJoin allows joining existing rooms. Also gates room
 * visibility: a user sees a room in their room list iff they are
 * already a member OR `room.join` resolves to allow at the room.
 * (There is no separate `room.list` permission — having a "you can
 * see it but can't join it" tier added cognitive load with no
 * product use case to justify it.)
 */
export const PermRoomJoin: Permission = "room.join";
/**
 * PermRoomManage allows updating or deleting any room.
 */
export const PermRoomManage: Permission = "room.manage";
/**
 * PermMessagePost allows posting new root messages in a room.
 */
export const PermMessagePost: Permission = "message.post";
/**
 * PermMessagePostInThread allows posting messages in a thread (first or subsequent reply).
 */
export const PermMessagePostInThread: Permission = "message.post-in-thread";
/**
 * PermMessageReply allows using reply attribution (inReplyTo). Covers
 * both room-level and in-thread replies — the destination is gated by
 * message.post / message.post-in-thread, this permission just controls
 * whether reply attribution is allowed at all.
 */
export const PermMessageReply: Permission = "message.reply";
/**
 * PermMessageManage allows moderating other users' messages in a room
 * (editing or deleting). The actor must also strictly outrank the
 * message author — enforced at the API boundary. Authors editing or
 * deleting their own messages do NOT need this permission; it is
 * always allowed.
 */
export const PermMessageManage: Permission = "message.manage";
/**
 * PermMessageReact allows adding/removing reactions to messages.
 */
export const PermMessageReact: Permission = "message.react";
/**
 * PermMessageEcho allows echoing thread replies to the main channel.
 */
export const PermMessageEcho: Permission = "message.echo";
/**
 * PermRoleManage allows creating, editing, deleting, and reordering roles
 * and their permission grants. Single canonical permission for "manage the
 * server's role definitions" (formerly split between role.manage and
 * admin.manage-roles).
 */
export const PermRoleManage: Permission = "role.manage";
/**
 * PermRoleAssign allows assigning and revoking roles to/from users.
 * Single canonical permission for "manage user role assignments"
 * (formerly split between role.assign and admin.manage-users).
 */
export const PermRoleAssign: Permission = "role.assign";
/**
 * PermAdminAccess allows access to the admin panel.
 */
export const PermAdminAccess: Permission = "admin.access";
/**
 * PermAdminUsersView allows viewing the users page in admin.
 */
export const PermAdminUsersView: Permission = "admin.view-users";
/**
 * PermAdminSystemView allows viewing system and data pages in admin.
 */
export const PermAdminSystemView: Permission = "admin.view-system";
/**
 * PermAdminAuditView allows viewing the audit log in admin.
 */
export const PermAdminAuditView: Permission = "admin.view-audit";
/**
 * PermDMView allows accessing DMs and reading direct messages.
 */
export const PermDMView: Permission = "dm.view";
/**
 * PermDMWrite allows starting DM conversations and sending messages.
 */
export const PermDMWrite: Permission = "dm.write";
/**
 * PermUserDeleteAny allows admins to delete any user's account.
 * Mirrors message.delete-any: the actor needs the permission AND
 * must strictly outrank the target user (rank check enforced at the
 * API boundary when the cross-user delete mutation is implemented).
 */
export const PermUserDeleteAny: Permission = "user.delete-any";
/**
 * PermUserDeleteSelf allows users to delete their own account.
 */
export const PermUserDeleteSelf: Permission = "user.delete-self";
/**
 * PermissionMetadata provides display information and scope constraints for a permission.
 */
export interface PermissionMetadata {
  Permission: Permission;
  DisplayName: string;
  Description: string;
  Category: PermissionCategory;
  Scopes: PermissionScope[]; // Scopes where this permission can be configured
}
/**
 * PermissionKeyParts holds the verb and objectType components for KV key generation.
 * Permission strings follow the format "{objectType}.{verb}" (e.g., "room.create",
 * "message.delete-own", "admin.view-users"), so key parts are derived directly from
 * the permission string — no separate mapping needed.
 */
export interface PermissionKeyParts {
  Verb: string; // The action: "create", "join", "delete-own", "view-users", etc.
  ObjectType: string; // The target type: "server", "room", "message", "admin", etc.
}
