// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/attachments.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { MessageAttachment } from "./message_types_pb.js";
import { ImageTransformOptions } from "./common_pb.js";

/**
 * One current room attachment and its message anchor.
 *
 * @generated from message chatto.api.v1.RoomAttachmentListItem
 */
export class RoomAttachmentListItem extends Message<RoomAttachmentListItem> {
  /**
   * Attachment metadata and signed URLs.
   *
   * @generated from field: chatto.api.v1.MessageAttachment attachment = 1;
   */
  attachment?: MessageAttachment;

  /**
   * Message event containing the attachment.
   *
   * @generated from field: string message_event_id = 2;
   */
  messageEventId = "";

  /**
   * Thread root event ID when the containing message is a thread reply.
   *
   * @generated from field: string thread_root_event_id = 3;
   */
  threadRootEventId = "";

  /**
   * Message creation timestamp.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<RoomAttachmentListItem>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.RoomAttachmentListItem";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "attachment", kind: "message", T: MessageAttachment },
    { no: 2, name: "message_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "thread_root_event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RoomAttachmentListItem {
    return new RoomAttachmentListItem().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RoomAttachmentListItem {
    return new RoomAttachmentListItem().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RoomAttachmentListItem {
    return new RoomAttachmentListItem().fromJsonString(jsonString, options);
  }

  static equals(a: RoomAttachmentListItem | PlainMessage<RoomAttachmentListItem> | undefined, b: RoomAttachmentListItem | PlainMessage<RoomAttachmentListItem> | undefined): boolean {
    return proto3.util.equals(RoomAttachmentListItem, a, b);
  }
}

/**
 * Request to read one room-scoped asset with freshly signed URLs.
 *
 * @generated from message chatto.api.v1.GetAssetRequest
 */
export class GetAssetRequest extends Message<GetAssetRequest> {
  /**
   * Required. Room that owns the asset.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Asset ID.
   *
   * @generated from field: string asset_id = 2;
   */
  assetId = "";

  /**
   * Thumbnail URL options. Defaults are applied when absent.
   *
   * @generated from field: chatto.api.v1.ImageTransformOptions thumbnail = 3;
   */
  thumbnail?: ImageTransformOptions;

  constructor(data?: PartialMessage<GetAssetRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetAssetRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "thumbnail", kind: "message", T: ImageTransformOptions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAssetRequest {
    return new GetAssetRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAssetRequest {
    return new GetAssetRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAssetRequest {
    return new GetAssetRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAssetRequest | PlainMessage<GetAssetRequest> | undefined, b: GetAssetRequest | PlainMessage<GetAssetRequest> | undefined): boolean {
    return proto3.util.equals(GetAssetRequest, a, b);
  }
}

/**
 * Response containing one room-scoped asset.
 *
 * @generated from message chatto.api.v1.GetAssetResponse
 */
export class GetAssetResponse extends Message<GetAssetResponse> {
  /**
   * Asset metadata and signed URLs.
   *
   * @generated from field: chatto.api.v1.MessageAttachment asset = 1;
   */
  asset?: MessageAttachment;

  constructor(data?: PartialMessage<GetAssetResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetAssetResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset", kind: "message", T: MessageAttachment },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAssetResponse {
    return new GetAssetResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAssetResponse {
    return new GetAssetResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAssetResponse {
    return new GetAssetResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAssetResponse | PlainMessage<GetAssetResponse> | undefined, b: GetAssetResponse | PlainMessage<GetAssetResponse> | undefined): boolean {
    return proto3.util.equals(GetAssetResponse, a, b);
  }
}

/**
 * Request to read many room-scoped assets with freshly signed URLs.
 *
 * @generated from message chatto.api.v1.BatchGetAssetsRequest
 */
export class BatchGetAssetsRequest extends Message<BatchGetAssetsRequest> {
  /**
   * Required. Room that owns the assets.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. Asset IDs. Missing, deleted, and wrong-room asset IDs are omitted.
   *
   * @generated from field: repeated string asset_ids = 2;
   */
  assetIds: string[] = [];

  /**
   * Thumbnail URL options. Defaults are applied when absent.
   *
   * @generated from field: chatto.api.v1.ImageTransformOptions thumbnail = 3;
   */
  thumbnail?: ImageTransformOptions;

  constructor(data?: PartialMessage<BatchGetAssetsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetAssetsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "asset_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "thumbnail", kind: "message", T: ImageTransformOptions },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetAssetsRequest {
    return new BatchGetAssetsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetAssetsRequest {
    return new BatchGetAssetsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetAssetsRequest {
    return new BatchGetAssetsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetAssetsRequest | PlainMessage<BatchGetAssetsRequest> | undefined, b: BatchGetAssetsRequest | PlainMessage<BatchGetAssetsRequest> | undefined): boolean {
    return proto3.util.equals(BatchGetAssetsRequest, a, b);
  }
}

/**
 * Response containing room-scoped assets.
 *
 * @generated from message chatto.api.v1.BatchGetAssetsResponse
 */
export class BatchGetAssetsResponse extends Message<BatchGetAssetsResponse> {
  /**
   * Assets in first-seen request order.
   *
   * @generated from field: repeated chatto.api.v1.MessageAttachment assets = 1;
   */
  assets: MessageAttachment[] = [];

  constructor(data?: PartialMessage<BatchGetAssetsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.BatchGetAssetsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "assets", kind: "message", T: MessageAttachment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BatchGetAssetsResponse {
    return new BatchGetAssetsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BatchGetAssetsResponse {
    return new BatchGetAssetsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BatchGetAssetsResponse {
    return new BatchGetAssetsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BatchGetAssetsResponse | PlainMessage<BatchGetAssetsResponse> | undefined, b: BatchGetAssetsResponse | PlainMessage<BatchGetAssetsResponse> | undefined): boolean {
    return proto3.util.equals(BatchGetAssetsResponse, a, b);
  }
}
