// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/member_directory.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BatchGetUsersRequest, BatchGetUsersResponse, GetUserRequest, GetUserResponse, ListUsersRequest, ListUsersResponse } from "./member_directory_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Reads the authenticated server-wide user directory.
 *
 * @generated from service chatto.api.v1.UserService
 */
export const UserService = {
  typeName: "chatto.api.v1.UserService",
  methods: {
    /**
     * Lists users visible to the authenticated user. Admin-sensitive account
     * fields stay out of this public row shape.
     *
     * @generated from rpc chatto.api.v1.UserService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one visible user by user ID or login. Returns NOT_FOUND when the
     * target is unknown.
     *
     * @generated from rpc chatto.api.v1.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets visible user rows for multiple stable user IDs. Unknown IDs are
     * omitted from the response.
     *
     * @generated from rpc chatto.api.v1.UserService.BatchGetUsers
     */
    batchGetUsers: {
      name: "BatchGetUsers",
      I: BatchGetUsersRequest,
      O: BatchGetUsersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
