// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file chatto/api/v1/notification_preferences.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Notification delivery level for a room.
 *
 * @generated from enum chatto.api.v1.NotificationLevel
 */
export enum NotificationLevel {
  /**
   * The level was not specified.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Use the inherited default for the room.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_DEFAULT = 1;
   */
  DEFAULT = 1,

  /**
   * Do not notify for this room.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_MUTED = 2;
   */
  MUTED = 2,

  /**
   * Notify according to the normal room rules.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_NORMAL = 3;
   */
  NORMAL = 3,

  /**
   * Notify for every message in the room.
   *
   * @generated from enum value: NOTIFICATION_LEVEL_ALL_MESSAGES = 4;
   */
  ALL_MESSAGES = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(NotificationLevel)
proto3.util.setEnumType(NotificationLevel, "chatto.api.v1.NotificationLevel", [
  { no: 0, name: "NOTIFICATION_LEVEL_UNSPECIFIED" },
  { no: 1, name: "NOTIFICATION_LEVEL_DEFAULT" },
  { no: 2, name: "NOTIFICATION_LEVEL_MUTED" },
  { no: 3, name: "NOTIFICATION_LEVEL_NORMAL" },
  { no: 4, name: "NOTIFICATION_LEVEL_ALL_MESSAGES" },
]);

/**
 * Stored and effective notification preference.
 *
 * @generated from message chatto.api.v1.NotificationPreference
 */
export class NotificationPreference extends Message<NotificationPreference> {
  /**
   * Explicit level stored for the current user.
   *
   * @generated from field: chatto.api.v1.NotificationLevel level = 1;
   */
  level = NotificationLevel.UNSPECIFIED;

  /**
   * Level after applying defaults and inheritance.
   *
   * @generated from field: chatto.api.v1.NotificationLevel effective_level = 2;
   */
  effectiveLevel = NotificationLevel.UNSPECIFIED;

  constructor(data?: PartialMessage<NotificationPreference>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.NotificationPreference";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
    { no: 2, name: "effective_level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NotificationPreference {
    return new NotificationPreference().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NotificationPreference {
    return new NotificationPreference().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NotificationPreference {
    return new NotificationPreference().fromJsonString(jsonString, options);
  }

  static equals(a: NotificationPreference | PlainMessage<NotificationPreference> | undefined, b: NotificationPreference | PlainMessage<NotificationPreference> | undefined): boolean {
    return proto3.util.equals(NotificationPreference, a, b);
  }
}

/**
 * Current notification preference for a room.
 *
 * @generated from message chatto.api.v1.GetRoomNotificationPreferenceResponse
 */
export class GetRoomNotificationPreferenceResponse extends Message<GetRoomNotificationPreferenceResponse> {
  /**
   * Current stored and effective notification preference.
   *
   * @generated from field: chatto.api.v1.NotificationPreference preference = 3;
   */
  preference?: NotificationPreference;

  constructor(data?: PartialMessage<GetRoomNotificationPreferenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomNotificationPreferenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "preference", kind: "message", T: NotificationPreference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomNotificationPreferenceResponse {
    return new GetRoomNotificationPreferenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomNotificationPreferenceResponse {
    return new GetRoomNotificationPreferenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomNotificationPreferenceResponse {
    return new GetRoomNotificationPreferenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomNotificationPreferenceResponse | PlainMessage<GetRoomNotificationPreferenceResponse> | undefined, b: GetRoomNotificationPreferenceResponse | PlainMessage<GetRoomNotificationPreferenceResponse> | undefined): boolean {
    return proto3.util.equals(GetRoomNotificationPreferenceResponse, a, b);
  }
}

/**
 * Updated notification preference for a room.
 *
 * @generated from message chatto.api.v1.UpdateRoomNotificationPreferenceResponse
 */
export class UpdateRoomNotificationPreferenceResponse extends Message<UpdateRoomNotificationPreferenceResponse> {
  /**
   * Stored and effective notification preference after the update.
   *
   * @generated from field: chatto.api.v1.NotificationPreference preference = 3;
   */
  preference?: NotificationPreference;

  constructor(data?: PartialMessage<UpdateRoomNotificationPreferenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateRoomNotificationPreferenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "preference", kind: "message", T: NotificationPreference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRoomNotificationPreferenceResponse {
    return new UpdateRoomNotificationPreferenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRoomNotificationPreferenceResponse {
    return new UpdateRoomNotificationPreferenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRoomNotificationPreferenceResponse {
    return new UpdateRoomNotificationPreferenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRoomNotificationPreferenceResponse | PlainMessage<UpdateRoomNotificationPreferenceResponse> | undefined, b: UpdateRoomNotificationPreferenceResponse | PlainMessage<UpdateRoomNotificationPreferenceResponse> | undefined): boolean {
    return proto3.util.equals(UpdateRoomNotificationPreferenceResponse, a, b);
  }
}

/**
 * Current server-level notification preference.
 *
 * @generated from message chatto.api.v1.GetServerNotificationPreferenceResponse
 */
export class GetServerNotificationPreferenceResponse extends Message<GetServerNotificationPreferenceResponse> {
  /**
   * Current stored and effective notification preference.
   *
   * @generated from field: chatto.api.v1.NotificationPreference preference = 3;
   */
  preference?: NotificationPreference;

  constructor(data?: PartialMessage<GetServerNotificationPreferenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetServerNotificationPreferenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "preference", kind: "message", T: NotificationPreference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerNotificationPreferenceResponse {
    return new GetServerNotificationPreferenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerNotificationPreferenceResponse {
    return new GetServerNotificationPreferenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerNotificationPreferenceResponse {
    return new GetServerNotificationPreferenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerNotificationPreferenceResponse | PlainMessage<GetServerNotificationPreferenceResponse> | undefined, b: GetServerNotificationPreferenceResponse | PlainMessage<GetServerNotificationPreferenceResponse> | undefined): boolean {
    return proto3.util.equals(GetServerNotificationPreferenceResponse, a, b);
  }
}

/**
 * Updated server-level notification preference.
 *
 * @generated from message chatto.api.v1.UpdateServerNotificationPreferenceResponse
 */
export class UpdateServerNotificationPreferenceResponse extends Message<UpdateServerNotificationPreferenceResponse> {
  /**
   * Stored and effective notification preference after the update.
   *
   * @generated from field: chatto.api.v1.NotificationPreference preference = 3;
   */
  preference?: NotificationPreference;

  constructor(data?: PartialMessage<UpdateServerNotificationPreferenceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateServerNotificationPreferenceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 3, name: "preference", kind: "message", T: NotificationPreference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateServerNotificationPreferenceResponse {
    return new UpdateServerNotificationPreferenceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateServerNotificationPreferenceResponse {
    return new UpdateServerNotificationPreferenceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateServerNotificationPreferenceResponse {
    return new UpdateServerNotificationPreferenceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateServerNotificationPreferenceResponse | PlainMessage<UpdateServerNotificationPreferenceResponse> | undefined, b: UpdateServerNotificationPreferenceResponse | PlainMessage<UpdateServerNotificationPreferenceResponse> | undefined): boolean {
    return proto3.util.equals(UpdateServerNotificationPreferenceResponse, a, b);
  }
}

/**
 * Request for the current user's server-level notification preference.
 *
 * @generated from message chatto.api.v1.GetServerNotificationPreferenceRequest
 */
export class GetServerNotificationPreferenceRequest extends Message<GetServerNotificationPreferenceRequest> {
  constructor(data?: PartialMessage<GetServerNotificationPreferenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetServerNotificationPreferenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetServerNotificationPreferenceRequest {
    return new GetServerNotificationPreferenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetServerNotificationPreferenceRequest {
    return new GetServerNotificationPreferenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetServerNotificationPreferenceRequest {
    return new GetServerNotificationPreferenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetServerNotificationPreferenceRequest | PlainMessage<GetServerNotificationPreferenceRequest> | undefined, b: GetServerNotificationPreferenceRequest | PlainMessage<GetServerNotificationPreferenceRequest> | undefined): boolean {
    return proto3.util.equals(GetServerNotificationPreferenceRequest, a, b);
  }
}

/**
 * Request to update the current user's server-level notification level.
 *
 * @generated from message chatto.api.v1.UpdateServerNotificationPreferenceRequest
 */
export class UpdateServerNotificationPreferenceRequest extends Message<UpdateServerNotificationPreferenceRequest> {
  /**
   * Required. New explicit notification level. Use NOTIFICATION_LEVEL_DEFAULT
   * to return the server to default behavior.
   *
   * @generated from field: chatto.api.v1.NotificationLevel level = 1;
   */
  level = NotificationLevel.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateServerNotificationPreferenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateServerNotificationPreferenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateServerNotificationPreferenceRequest {
    return new UpdateServerNotificationPreferenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateServerNotificationPreferenceRequest {
    return new UpdateServerNotificationPreferenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateServerNotificationPreferenceRequest {
    return new UpdateServerNotificationPreferenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateServerNotificationPreferenceRequest | PlainMessage<UpdateServerNotificationPreferenceRequest> | undefined, b: UpdateServerNotificationPreferenceRequest | PlainMessage<UpdateServerNotificationPreferenceRequest> | undefined): boolean {
    return proto3.util.equals(UpdateServerNotificationPreferenceRequest, a, b);
  }
}

/**
 * Request for the current user's notification preference in one room.
 *
 * @generated from message chatto.api.v1.GetRoomNotificationPreferenceRequest
 */
export class GetRoomNotificationPreferenceRequest extends Message<GetRoomNotificationPreferenceRequest> {
  /**
   * Required. Room whose notification preference should be loaded for the current user.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  constructor(data?: PartialMessage<GetRoomNotificationPreferenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.GetRoomNotificationPreferenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetRoomNotificationPreferenceRequest {
    return new GetRoomNotificationPreferenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetRoomNotificationPreferenceRequest {
    return new GetRoomNotificationPreferenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetRoomNotificationPreferenceRequest {
    return new GetRoomNotificationPreferenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetRoomNotificationPreferenceRequest | PlainMessage<GetRoomNotificationPreferenceRequest> | undefined, b: GetRoomNotificationPreferenceRequest | PlainMessage<GetRoomNotificationPreferenceRequest> | undefined): boolean {
    return proto3.util.equals(GetRoomNotificationPreferenceRequest, a, b);
  }
}

/**
 * Request to update the current user's notification level in one room.
 *
 * @generated from message chatto.api.v1.UpdateRoomNotificationPreferenceRequest
 */
export class UpdateRoomNotificationPreferenceRequest extends Message<UpdateRoomNotificationPreferenceRequest> {
  /**
   * Required. Room whose notification level should be changed for the current user.
   *
   * @generated from field: string room_id = 1;
   */
  roomId = "";

  /**
   * Required. New explicit notification level. Use NOTIFICATION_LEVEL_DEFAULT
   * to return the room to inherited/default behavior.
   *
   * @generated from field: chatto.api.v1.NotificationLevel level = 2;
   */
  level = NotificationLevel.UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateRoomNotificationPreferenceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.api.v1.UpdateRoomNotificationPreferenceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "room_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "level", kind: "enum", T: proto3.getEnumType(NotificationLevel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateRoomNotificationPreferenceRequest {
    return new UpdateRoomNotificationPreferenceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateRoomNotificationPreferenceRequest {
    return new UpdateRoomNotificationPreferenceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateRoomNotificationPreferenceRequest {
    return new UpdateRoomNotificationPreferenceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateRoomNotificationPreferenceRequest | PlainMessage<UpdateRoomNotificationPreferenceRequest> | undefined, b: UpdateRoomNotificationPreferenceRequest | PlainMessage<UpdateRoomNotificationPreferenceRequest> | undefined): boolean {
    return proto3.util.equals(UpdateRoomNotificationPreferenceRequest, a, b);
  }
}
