// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/server_state.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetServerStateRequest, GetServerStateResponse } from "./server_state_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { BatchGetServerMembersRequest, BatchGetServerMembersResponse, GetServerMemberRequest, GetServerMemberResponse, ListServerMembersRequest, ListServerMembersResponse } from "./member_directory_pb.js";

/**
 * Provides authenticated server profile, runtime configuration, and public
 * server member reads.
 *
 * @generated from service chatto.api.v1.ServerService
 */
export const ServerService = {
  typeName: "chatto.api.v1.ServerService",
  methods: {
    /**
     * Returns authenticated server state. This RPC requires a logged-in user;
     * public discovery remains available through
     * chatto.discovery.v1.ServerDiscoveryService.GetServer.
     *
     * @generated from rpc chatto.api.v1.ServerService.GetServerState
     */
    getServerState: {
      name: "GetServerState",
      I: GetServerStateRequest,
      O: GetServerStateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists authenticated server members. Every authenticated user is a server
     * member; admin-sensitive fields stay out of this public row shape.
     *
     * @generated from rpc chatto.api.v1.ServerService.ListMembers
     */
    listMembers: {
      name: "ListMembers",
      I: ListServerMembersRequest,
      O: ListServerMembersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets one authenticated server member. Returns NOT_FOUND when the user ID is
     * unknown.
     *
     * @generated from rpc chatto.api.v1.ServerService.GetMember
     */
    getMember: {
      name: "GetMember",
      I: GetServerMemberRequest,
      O: GetServerMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Gets authenticated server member rows for multiple users.
     *
     * @generated from rpc chatto.api.v1.ServerService.BatchGetMembers
     */
    batchGetMembers: {
      name: "BatchGetMembers",
      I: BatchGetServerMembersRequest,
      O: BatchGetServerMembersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
