// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/auth_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditRequestMetadata captures request details that are safe to persist in
// the durable audit log. Raw IP addresses, links, and tokens never belong here.
type AuditRequestMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgent     string                 `protobuf:"bytes,1,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IpHash        string                 `protobuf:"bytes,2,opt,name=ip_hash,json=ipHash,proto3" json:"ip_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequestMetadata) Reset() {
	*x = AuditRequestMetadata{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequestMetadata) ProtoMessage() {}

func (x *AuditRequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequestMetadata.ProtoReflect.Descriptor instead.
func (*AuditRequestMetadata) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{0}
}

func (x *AuditRequestMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditRequestMetadata) GetIpHash() string {
	if x != nil {
		return x.IpHash
	}
	return ""
}

type RegistrationLinkIssuedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailHash     string                 `protobuf:"bytes,1,opt,name=email_hash,json=emailHash,proto3" json:"email_hash,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationLinkIssuedEvent) Reset() {
	*x = RegistrationLinkIssuedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationLinkIssuedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationLinkIssuedEvent) ProtoMessage() {}

func (x *RegistrationLinkIssuedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationLinkIssuedEvent.ProtoReflect.Descriptor instead.
func (*RegistrationLinkIssuedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationLinkIssuedEvent) GetEmailHash() string {
	if x != nil {
		return x.EmailHash
	}
	return ""
}

func (x *RegistrationLinkIssuedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RegistrationLinkIssuedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type EmailVerificationLinkIssuedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailHash     string                 `protobuf:"bytes,2,opt,name=email_hash,json=emailHash,proto3" json:"email_hash,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerificationLinkIssuedEvent) Reset() {
	*x = EmailVerificationLinkIssuedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationLinkIssuedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationLinkIssuedEvent) ProtoMessage() {}

func (x *EmailVerificationLinkIssuedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationLinkIssuedEvent.ProtoReflect.Descriptor instead.
func (*EmailVerificationLinkIssuedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{2}
}

func (x *EmailVerificationLinkIssuedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmailVerificationLinkIssuedEvent) GetEmailHash() string {
	if x != nil {
		return x.EmailHash
	}
	return ""
}

func (x *EmailVerificationLinkIssuedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EmailVerificationLinkIssuedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type PasswordResetLinkIssuedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailHash     string                 `protobuf:"bytes,2,opt,name=email_hash,json=emailHash,proto3" json:"email_hash,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetLinkIssuedEvent) Reset() {
	*x = PasswordResetLinkIssuedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetLinkIssuedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetLinkIssuedEvent) ProtoMessage() {}

func (x *PasswordResetLinkIssuedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetLinkIssuedEvent.ProtoReflect.Descriptor instead.
func (*PasswordResetLinkIssuedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordResetLinkIssuedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordResetLinkIssuedEvent) GetEmailHash() string {
	if x != nil {
		return x.EmailHash
	}
	return ""
}

func (x *PasswordResetLinkIssuedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PasswordResetLinkIssuedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type AccountDeletionConfirmationIssuedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDeletionConfirmationIssuedEvent) Reset() {
	*x = AccountDeletionConfirmationIssuedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDeletionConfirmationIssuedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeletionConfirmationIssuedEvent) ProtoMessage() {}

func (x *AccountDeletionConfirmationIssuedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeletionConfirmationIssuedEvent.ProtoReflect.Descriptor instead.
func (*AccountDeletionConfirmationIssuedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{4}
}

func (x *AccountDeletionConfirmationIssuedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountDeletionConfirmationIssuedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AccountDeletionConfirmationIssuedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type PasswordResetCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetCompletedEvent) Reset() {
	*x = PasswordResetCompletedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetCompletedEvent) ProtoMessage() {}

func (x *PasswordResetCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetCompletedEvent.ProtoReflect.Descriptor instead.
func (*PasswordResetCompletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{5}
}

func (x *PasswordResetCompletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordResetCompletedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type LoginSucceededEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentifierHash string                 `protobuf:"bytes,2,opt,name=identifier_hash,json=identifierHash,proto3" json:"identifier_hash,omitempty"`
	Request        *AuditRequestMetadata  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginSucceededEvent) Reset() {
	*x = LoginSucceededEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSucceededEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSucceededEvent) ProtoMessage() {}

func (x *LoginSucceededEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSucceededEvent.ProtoReflect.Descriptor instead.
func (*LoginSucceededEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{6}
}

func (x *LoginSucceededEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginSucceededEvent) GetIdentifierHash() string {
	if x != nil {
		return x.IdentifierHash
	}
	return ""
}

func (x *LoginSucceededEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type LoginFailedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentifierHash string                 `protobuf:"bytes,1,opt,name=identifier_hash,json=identifierHash,proto3" json:"identifier_hash,omitempty"`
	Request        *AuditRequestMetadata  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginFailedEvent) Reset() {
	*x = LoginFailedEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFailedEvent) ProtoMessage() {}

func (x *LoginFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFailedEvent.ProtoReflect.Descriptor instead.
func (*LoginFailedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{7}
}

func (x *LoginFailedEvent) GetIdentifierHash() string {
	if x != nil {
		return x.IdentifierHash
	}
	return ""
}

func (x *LoginFailedEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

type LogoutSucceededEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Request       *AuditRequestMetadata  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutSucceededEvent) Reset() {
	*x = LogoutSucceededEvent{}
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutSucceededEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutSucceededEvent) ProtoMessage() {}

func (x *LogoutSucceededEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_auth_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutSucceededEvent.ProtoReflect.Descriptor instead.
func (*LogoutSucceededEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_auth_events_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutSucceededEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogoutSucceededEvent) GetRequest() *AuditRequestMetadata {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_chatto_core_v1_auth_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_auth_events_proto_rawDesc = "" +
	"\n" +
	" chatto/core/v1/auth_events.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x14AuditRequestMetadata\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x01 \x01(\tR\tuserAgent\x12\x17\n" +
	"\aip_hash\x18\x02 \x01(\tR\x06ipHash\"\xb7\x01\n" +
	"\x1bRegistrationLinkIssuedEvent\x12\x1d\n" +
	"\n" +
	"email_hash\x18\x01 \x01(\tR\temailHash\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\arequest\x18\x03 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"\xd5\x01\n" +
	" EmailVerificationLinkIssuedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"email_hash\x18\x02 \x01(\tR\temailHash\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\arequest\x18\x04 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"\xd1\x01\n" +
	"\x1cPasswordResetLinkIssuedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"email_hash\x18\x02 \x01(\tR\temailHash\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\arequest\x18\x04 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"\xbc\x01\n" +
	"&AccountDeletionConfirmationIssuedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\arequest\x18\x03 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"v\n" +
	"\x1bPasswordResetCompletedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\arequest\x18\x02 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"\x97\x01\n" +
	"\x13LoginSucceededEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fidentifier_hash\x18\x02 \x01(\tR\x0eidentifierHash\x12>\n" +
	"\arequest\x18\x03 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"{\n" +
	"\x10LoginFailedEvent\x12'\n" +
	"\x0fidentifier_hash\x18\x01 \x01(\tR\x0eidentifierHash\x12>\n" +
	"\arequest\x18\x02 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequest\"o\n" +
	"\x14LogoutSucceededEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\arequest\x18\x02 \x01(\v2$.chatto.core.v1.AuditRequestMetadataR\arequestB\xb2\x01\n" +
	"\x12com.chatto.core.v1B\x0fAuthEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_auth_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_auth_events_proto_rawDescData []byte
)

func file_chatto_core_v1_auth_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_auth_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_auth_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_auth_events_proto_rawDesc), len(file_chatto_core_v1_auth_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_auth_events_proto_rawDescData
}

var file_chatto_core_v1_auth_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chatto_core_v1_auth_events_proto_goTypes = []any{
	(*AuditRequestMetadata)(nil),                   // 0: chatto.core.v1.AuditRequestMetadata
	(*RegistrationLinkIssuedEvent)(nil),            // 1: chatto.core.v1.RegistrationLinkIssuedEvent
	(*EmailVerificationLinkIssuedEvent)(nil),       // 2: chatto.core.v1.EmailVerificationLinkIssuedEvent
	(*PasswordResetLinkIssuedEvent)(nil),           // 3: chatto.core.v1.PasswordResetLinkIssuedEvent
	(*AccountDeletionConfirmationIssuedEvent)(nil), // 4: chatto.core.v1.AccountDeletionConfirmationIssuedEvent
	(*PasswordResetCompletedEvent)(nil),            // 5: chatto.core.v1.PasswordResetCompletedEvent
	(*LoginSucceededEvent)(nil),                    // 6: chatto.core.v1.LoginSucceededEvent
	(*LoginFailedEvent)(nil),                       // 7: chatto.core.v1.LoginFailedEvent
	(*LogoutSucceededEvent)(nil),                   // 8: chatto.core.v1.LogoutSucceededEvent
	(*timestamppb.Timestamp)(nil),                  // 9: google.protobuf.Timestamp
}
var file_chatto_core_v1_auth_events_proto_depIdxs = []int32{
	9,  // 0: chatto.core.v1.RegistrationLinkIssuedEvent.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: chatto.core.v1.RegistrationLinkIssuedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	9,  // 2: chatto.core.v1.EmailVerificationLinkIssuedEvent.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: chatto.core.v1.EmailVerificationLinkIssuedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	9,  // 4: chatto.core.v1.PasswordResetLinkIssuedEvent.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: chatto.core.v1.PasswordResetLinkIssuedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	9,  // 6: chatto.core.v1.AccountDeletionConfirmationIssuedEvent.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: chatto.core.v1.AccountDeletionConfirmationIssuedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	0,  // 8: chatto.core.v1.PasswordResetCompletedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	0,  // 9: chatto.core.v1.LoginSucceededEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	0,  // 10: chatto.core.v1.LoginFailedEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	0,  // 11: chatto.core.v1.LogoutSucceededEvent.request:type_name -> chatto.core.v1.AuditRequestMetadata
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_auth_events_proto_init() }
func file_chatto_core_v1_auth_events_proto_init() {
	if File_chatto_core_v1_auth_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_auth_events_proto_rawDesc), len(file_chatto_core_v1_auth_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_auth_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_auth_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_auth_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_auth_events_proto = out.File
	file_chatto_core_v1_auth_events_proto_goTypes = nil
	file_chatto_core_v1_auth_events_proto_depIdxs = nil
}
