// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/live_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartbeatEvent is a synthetic event with no payload. StreamMyEvents
// emits one every ~25 seconds so clients can detect a dead subscription
// on an otherwise-healthy WebSocket. It is never persisted and never
// travels over NATS.
type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{0}
}

// NotificationLevelChangedEvent is published when a user changes their notification
// level for the server or a specific room. User-scoped: only delivered to the user
// who changed it.
type NotificationLevelChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room whose notification level was changed (empty for server-level changes).
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The explicitly set level.
	Level NotificationLevel `protobuf:"varint,3,opt,name=level,proto3,enum=chatto.core.v1.NotificationLevel" json:"level,omitempty"`
	// The effective level after inheritance resolution.
	EffectiveLevel NotificationLevel `protobuf:"varint,4,opt,name=effective_level,json=effectiveLevel,proto3,enum=chatto.core.v1.NotificationLevel" json:"effective_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationLevelChangedEvent) Reset() {
	*x = NotificationLevelChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLevelChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLevelChangedEvent) ProtoMessage() {}

func (x *NotificationLevelChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLevelChangedEvent.ProtoReflect.Descriptor instead.
func (*NotificationLevelChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationLevelChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotificationLevelChangedEvent) GetLevel() NotificationLevel {
	if x != nil {
		return x.Level
	}
	return NotificationLevel_NOTIFICATION_LEVEL_DEFAULT
}

func (x *NotificationLevelChangedEvent) GetEffectiveLevel() NotificationLevel {
	if x != nil {
		return x.EffectiveLevel
	}
	return NotificationLevel_NOTIFICATION_LEVEL_DEFAULT
}

type ServerCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCreatedEvent) Reset() {
	*x = ServerCreatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCreatedEvent) ProtoMessage() {}

func (x *ServerCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCreatedEvent.ProtoReflect.Descriptor instead.
func (*ServerCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{2}
}

func (x *ServerCreatedEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ServerUpdatedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServerId    string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// URL to the server's logo, or empty if no logo is set.
	LogoUrl string `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	// URL to the server's banner, or empty if no banner is set.
	BannerUrl     string `protobuf:"bytes,5,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdatedEvent) Reset() {
	*x = ServerUpdatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdatedEvent) ProtoMessage() {}

func (x *ServerUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ServerUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{3}
}

func (x *ServerUpdatedEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerUpdatedEvent) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ServerUpdatedEvent) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

type ServerDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDeletedEvent) Reset() {
	*x = ServerDeletedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDeletedEvent) ProtoMessage() {}

func (x *ServerDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDeletedEvent.ProtoReflect.Descriptor instead.
func (*ServerDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{4}
}

func (x *ServerDeletedEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Notifies clients that a user is typing in a room or thread.
// Published directly to NATS Core (bypasses JetStream storage).
// Clients should implement timeout-based clearing (e.g., 6 seconds).
type UserTypingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID where the user is typing
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Thread root event ID (optional). If set, the user is typing a reply in this thread.
	// If empty, the user is typing in the main room view.
	ThreadRootEventId *string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3,oneof" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserTypingEvent) Reset() {
	*x = UserTypingEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypingEvent) ProtoMessage() {}

func (x *UserTypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypingEvent.ProtoReflect.Descriptor instead.
func (*UserTypingEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{5}
}

func (x *UserTypingEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserTypingEvent) GetThreadRootEventId() string {
	if x != nil && x.ThreadRootEventId != nil {
		return *x.ThreadRootEventId
	}
	return ""
}

// Notifies clients that a user's presence status changed.
// Published when a user comes online, goes offline, or changes their status.
// The user whose presence changed is identified by the parent envelope's actor_id.
// Presence is server-wide; the server context is implicit in the subscription.
type PresenceChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's new presence status ("ONLINE", "OFFLINE", "AWAY", "DO_NOT_DISTURB")
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChangedEvent) Reset() {
	*x = PresenceChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChangedEvent) ProtoMessage() {}

func (x *PresenceChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChangedEvent.ProtoReflect.Descriptor instead.
func (*PresenceChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{6}
}

func (x *PresenceChangedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Notifies a user that they were mentioned in a message.
// Published as a server-scoped live event to the mentioned user.
// This is a transient notification — the KV bucket tracks persistent state.
type MentionNotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID where the mention occurred
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// User ID of the person who mentioned them (the message author)
	MentionedByUserId string `protobuf:"bytes,3,opt,name=mentioned_by_user_id,json=mentionedByUserId,proto3" json:"mentioned_by_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MentionNotificationEvent) Reset() {
	*x = MentionNotificationEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionNotificationEvent) ProtoMessage() {}

func (x *MentionNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionNotificationEvent.ProtoReflect.Descriptor instead.
func (*MentionNotificationEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{7}
}

func (x *MentionNotificationEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MentionNotificationEvent) GetMentionedByUserId() string {
	if x != nil {
		return x.MentionedByUserId
	}
	return ""
}

// Notifies a user that a new message was posted in a DM conversation they're part of.
// Published as a server-scoped live event to all participants except the sender.
// Every DM message triggers this notification (unlike mentions which are opt-in).
type NewDirectMessageNotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID of the DM conversation
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// User ID of the person who sent the message
	SenderId      string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDirectMessageNotificationEvent) Reset() {
	*x = NewDirectMessageNotificationEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDirectMessageNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDirectMessageNotificationEvent) ProtoMessage() {}

func (x *NewDirectMessageNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDirectMessageNotificationEvent.ProtoReflect.Descriptor instead.
func (*NewDirectMessageNotificationEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{8}
}

func (x *NewDirectMessageNotificationEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NewDirectMessageNotificationEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// Published when a new notification is created for a user.
// Enables real-time notification updates in the UI.
type NotificationCreatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The notification ID
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Navigation context (optional fields for routing)
	RoomId        string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventId       string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InReplyToId   string `protobuf:"bytes,5,opt,name=in_reply_to_id,json=inReplyToId,proto3" json:"in_reply_to_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationCreatedEvent) Reset() {
	*x = NotificationCreatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCreatedEvent) ProtoMessage() {}

func (x *NotificationCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCreatedEvent.ProtoReflect.Descriptor instead.
func (*NotificationCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{9}
}

func (x *NotificationCreatedEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetInReplyToId() string {
	if x != nil {
		return x.InReplyToId
	}
	return ""
}

// Published when a notification is dismissed by the user.
// Enables cross-device sync of dismissed notifications.
type NotificationDismissedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dismissed notification ID
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationDismissedEvent) Reset() {
	*x = NotificationDismissedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDismissedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDismissedEvent) ProtoMessage() {}

func (x *NotificationDismissedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDismissedEvent.ProtoReflect.Descriptor instead.
func (*NotificationDismissedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{10}
}

func (x *NotificationDismissedEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

// ThreadFollowChangedEvent is published when a user's thread follow state changes
// (follow or unfollow, including auto-follow on posting). User-scoped: delivered
// only to the user whose follow state changed, for multi-tab/multi-device sync.
type ThreadFollowChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room containing the thread.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The root event ID of the thread.
	ThreadRootEventId string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// Whether the user is now following (true) or not following (false).
	IsFollowing   bool `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadFollowChangedEvent) Reset() {
	*x = ThreadFollowChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadFollowChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadFollowChangedEvent) ProtoMessage() {}

func (x *ThreadFollowChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadFollowChangedEvent.ProtoReflect.Descriptor instead.
func (*ThreadFollowChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{11}
}

func (x *ThreadFollowChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

// Published to the user who marked a room as read. This enables real-time
// updates to other tabs/devices for the same user.
type RoomMarkedAsReadEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID that was marked as read
	RoomId        string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMarkedAsReadEvent) Reset() {
	*x = RoomMarkedAsReadEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMarkedAsReadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMarkedAsReadEvent) ProtoMessage() {}

func (x *RoomMarkedAsReadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMarkedAsReadEvent.ProtoReflect.Descriptor instead.
func (*RoomMarkedAsReadEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{12}
}

func (x *RoomMarkedAsReadEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Published to the user whose mention indicator for a room was cleared.
// Fires whenever the server-side mention KV flag (`room_mention_status.*`) is
// deleted — that happens when the user marks a room as read (auto on entry or
// explicit) or dismisses a mention notification on any device. Other devices
// use this to drop the orange dot for the room without waiting for a refetch.
type MentionStatusClearedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID whose mention indicator was cleared
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionStatusClearedEvent) Reset() {
	*x = MentionStatusClearedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionStatusClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionStatusClearedEvent) ProtoMessage() {}

func (x *MentionStatusClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionStatusClearedEvent.ProtoReflect.Descriptor instead.
func (*MentionStatusClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{13}
}

func (x *MentionStatusClearedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Notifies clients that the channel-room groups (their ordering, names,
// or membership) were updated. Clients should refetch `Server.roomGroups`.
// Published as a live server event (not stored in JetStream).
type RoomGroupsUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGroupsUpdatedEvent) Reset() {
	*x = RoomGroupsUpdatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGroupsUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGroupsUpdatedEvent) ProtoMessage() {}

func (x *RoomGroupsUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGroupsUpdatedEvent.ProtoReflect.Descriptor instead.
func (*RoomGroupsUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{14}
}

// Notifies a user that their session has been terminated.
// Published as a user-scoped event on logout or admin boot.
// The subscription handler closes the stream after forwarding this event,
// ensuring the WebSocket connection is torn down server-side.
type SessionTerminatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason for termination: "logout", "admin_boot", "account_deleted"
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTerminatedEvent) Reset() {
	*x = SessionTerminatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTerminatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTerminatedEvent) ProtoMessage() {}

func (x *SessionTerminatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTerminatedEvent.ProtoReflect.Descriptor instead.
func (*SessionTerminatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{15}
}

func (x *SessionTerminatedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Notifies clients that video processing has completed (or failed) for an attachment.
// Published on the room's live subject so room subscribers receive it.
type VideoProcessingCompletedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID containing the message with the video
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Attachment ID of the original video
	AttachmentId string `protobuf:"bytes,3,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// Message body ID (internal, used by core for KV lookups)
	MessageBodyId string `protobuf:"bytes,4,opt,name=message_body_id,json=messageBodyId,proto3" json:"message_body_id,omitempty"`
	// Event ID of the message containing the attachment (for GraphQL API consumers).
	// Populated at publish time from the body key.
	MessageEventId string `protobuf:"bytes,5,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoProcessingCompletedEvent) Reset() {
	*x = VideoProcessingCompletedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoProcessingCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoProcessingCompletedEvent) ProtoMessage() {}

func (x *VideoProcessingCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoProcessingCompletedEvent.ProtoReflect.Descriptor instead.
func (*VideoProcessingCompletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{16}
}

func (x *VideoProcessingCompletedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VideoProcessingCompletedEvent) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *VideoProcessingCompletedEvent) GetMessageBodyId() string {
	if x != nil {
		return x.MessageBodyId
	}
	return ""
}

func (x *VideoProcessingCompletedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// Notifies room members that a user joined a voice call.
// Published as a live room event when a user requests a call token.
type CallParticipantJoinedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipantJoinedEvent) Reset() {
	*x = CallParticipantJoinedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipantJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipantJoinedEvent) ProtoMessage() {}

func (x *CallParticipantJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipantJoinedEvent.ProtoReflect.Descriptor instead.
func (*CallParticipantJoinedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{17}
}

func (x *CallParticipantJoinedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Notifies room members that a user left a voice call.
// Published as a live room event when a user explicitly leaves.
type CallParticipantLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallParticipantLeftEvent) Reset() {
	*x = CallParticipantLeftEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallParticipantLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallParticipantLeftEvent) ProtoMessage() {}

func (x *CallParticipantLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallParticipantLeftEvent.ProtoReflect.Descriptor instead.
func (*CallParticipantLeftEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{18}
}

func (x *CallParticipantLeftEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_chatto_core_v1_live_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_live_events_proto_rawDesc = "" +
	"\n" +
	" chatto/core/v1/live_events.proto\x12\x0echatto.core.v1\x1a%chatto/core/v1/user_preferences.proto\"\x10\n" +
	"\x0eHeartbeatEvent\"\xcd\x01\n" +
	"\x1dNotificationLevelChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x127\n" +
	"\x05level\x18\x03 \x01(\x0e2!.chatto.core.v1.NotificationLevelR\x05level\x12J\n" +
	"\x0feffective_level\x18\x04 \x01(\x0e2!.chatto.core.v1.NotificationLevelR\x0eeffectiveLevelJ\x04\b\x01\x10\x02R\bspace_id\"g\n" +
	"\x12ServerCreatedEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xa1\x01\n" +
	"\x12ServerUpdatedEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x05 \x01(\tR\tbannerUrl\"1\n" +
	"\x12ServerDeletedEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x89\x01\n" +
	"\x0fUserTypingEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x124\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tH\x00R\x11threadRootEventId\x88\x01\x01B\x17\n" +
	"\x15_thread_root_event_idJ\x04\b\x01\x10\x02R\bspace_id\".\n" +
	"\x14PresenceChangedEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"t\n" +
	"\x18MentionNotificationEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14mentioned_by_user_id\x18\x03 \x01(\tR\x11mentionedByUserIdJ\x04\b\x01\x10\x02R\bspace_id\"Y\n" +
	"!NewDirectMessageNotificationEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"\xac\x01\n" +
	"\x18NotificationCreatedEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12#\n" +
	"\x0ein_reply_to_id\x18\x05 \x01(\tR\vinReplyToIdJ\x04\b\x02\x10\x03R\bspace_id\"E\n" +
	"\x1aNotificationDismissedEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\x97\x01\n" +
	"\x18ThreadFollowChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x12!\n" +
	"\fis_following\x18\x04 \x01(\bR\visFollowingJ\x04\b\x01\x10\x02R\bspace_id\"@\n" +
	"\x15RoomMarkedAsReadEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomIdJ\x04\b\x01\x10\x02R\bspace_id\"4\n" +
	"\x19MentionStatusClearedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"(\n" +
	"\x16RoomGroupsUpdatedEventJ\x04\b\x01\x10\x02R\bspace_id\"0\n" +
	"\x16SessionTerminatedEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xbf\x01\n" +
	"\x1dVideoProcessingCompletedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12#\n" +
	"\rattachment_id\x18\x03 \x01(\tR\fattachmentId\x12&\n" +
	"\x0fmessage_body_id\x18\x04 \x01(\tR\rmessageBodyId\x12(\n" +
	"\x10message_event_id\x18\x05 \x01(\tR\x0emessageEventIdJ\x04\b\x01\x10\x02R\bspace_id\"E\n" +
	"\x1aCallParticipantJoinedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomIdJ\x04\b\x01\x10\x02R\bspace_id\"C\n" +
	"\x18CallParticipantLeftEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomIdJ\x04\b\x01\x10\x02R\bspace_idB\xb2\x01\n" +
	"\x12com.chatto.core.v1B\x0fLiveEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_live_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_live_events_proto_rawDescData []byte
)

func file_chatto_core_v1_live_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_live_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_live_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_live_events_proto_rawDesc), len(file_chatto_core_v1_live_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_live_events_proto_rawDescData
}

var file_chatto_core_v1_live_events_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chatto_core_v1_live_events_proto_goTypes = []any{
	(*HeartbeatEvent)(nil),                    // 0: chatto.core.v1.HeartbeatEvent
	(*NotificationLevelChangedEvent)(nil),     // 1: chatto.core.v1.NotificationLevelChangedEvent
	(*ServerCreatedEvent)(nil),                // 2: chatto.core.v1.ServerCreatedEvent
	(*ServerUpdatedEvent)(nil),                // 3: chatto.core.v1.ServerUpdatedEvent
	(*ServerDeletedEvent)(nil),                // 4: chatto.core.v1.ServerDeletedEvent
	(*UserTypingEvent)(nil),                   // 5: chatto.core.v1.UserTypingEvent
	(*PresenceChangedEvent)(nil),              // 6: chatto.core.v1.PresenceChangedEvent
	(*MentionNotificationEvent)(nil),          // 7: chatto.core.v1.MentionNotificationEvent
	(*NewDirectMessageNotificationEvent)(nil), // 8: chatto.core.v1.NewDirectMessageNotificationEvent
	(*NotificationCreatedEvent)(nil),          // 9: chatto.core.v1.NotificationCreatedEvent
	(*NotificationDismissedEvent)(nil),        // 10: chatto.core.v1.NotificationDismissedEvent
	(*ThreadFollowChangedEvent)(nil),          // 11: chatto.core.v1.ThreadFollowChangedEvent
	(*RoomMarkedAsReadEvent)(nil),             // 12: chatto.core.v1.RoomMarkedAsReadEvent
	(*MentionStatusClearedEvent)(nil),         // 13: chatto.core.v1.MentionStatusClearedEvent
	(*RoomGroupsUpdatedEvent)(nil),            // 14: chatto.core.v1.RoomGroupsUpdatedEvent
	(*SessionTerminatedEvent)(nil),            // 15: chatto.core.v1.SessionTerminatedEvent
	(*VideoProcessingCompletedEvent)(nil),     // 16: chatto.core.v1.VideoProcessingCompletedEvent
	(*CallParticipantJoinedEvent)(nil),        // 17: chatto.core.v1.CallParticipantJoinedEvent
	(*CallParticipantLeftEvent)(nil),          // 18: chatto.core.v1.CallParticipantLeftEvent
	(NotificationLevel)(0),                    // 19: chatto.core.v1.NotificationLevel
}
var file_chatto_core_v1_live_events_proto_depIdxs = []int32{
	19, // 0: chatto.core.v1.NotificationLevelChangedEvent.level:type_name -> chatto.core.v1.NotificationLevel
	19, // 1: chatto.core.v1.NotificationLevelChangedEvent.effective_level:type_name -> chatto.core.v1.NotificationLevel
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_live_events_proto_init() }
func file_chatto_core_v1_live_events_proto_init() {
	if File_chatto_core_v1_live_events_proto != nil {
		return
	}
	file_chatto_core_v1_user_preferences_proto_init()
	file_chatto_core_v1_live_events_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_live_events_proto_rawDesc), len(file_chatto_core_v1_live_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_live_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_live_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_live_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_live_events_proto = out.File
	file_chatto_core_v1_live_events_proto_goTypes = nil
	file_chatto_core_v1_live_events_proto_depIdxs = nil
}
