// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/rbac_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RbacRoleCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleCreatedEvent) Reset() {
	*x = RbacRoleCreatedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleCreatedEvent) ProtoMessage() {}

func (x *RbacRoleCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleCreatedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{0}
}

func (x *RbacRoleCreatedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RbacRoleCreatedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RbacRoleCreatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RbacRoleCreatedEvent) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type RbacRoleDisplayNameChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleDisplayNameChangedEvent) Reset() {
	*x = RbacRoleDisplayNameChangedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleDisplayNameChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleDisplayNameChangedEvent) ProtoMessage() {}

func (x *RbacRoleDisplayNameChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleDisplayNameChangedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleDisplayNameChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{1}
}

func (x *RbacRoleDisplayNameChangedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RbacRoleDisplayNameChangedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RbacRoleDescriptionChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleDescriptionChangedEvent) Reset() {
	*x = RbacRoleDescriptionChangedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleDescriptionChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleDescriptionChangedEvent) ProtoMessage() {}

func (x *RbacRoleDescriptionChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleDescriptionChangedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleDescriptionChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{2}
}

func (x *RbacRoleDescriptionChangedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RbacRoleDescriptionChangedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RbacRoleDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleDeletedEvent) Reset() {
	*x = RbacRoleDeletedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleDeletedEvent) ProtoMessage() {}

func (x *RbacRoleDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleDeletedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{3}
}

func (x *RbacRoleDeletedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RbacRolesReorderedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleNames     []string               `protobuf:"bytes,1,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRolesReorderedEvent) Reset() {
	*x = RbacRolesReorderedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRolesReorderedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRolesReorderedEvent) ProtoMessage() {}

func (x *RbacRolesReorderedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRolesReorderedEvent.ProtoReflect.Descriptor instead.
func (*RbacRolesReorderedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{4}
}

func (x *RbacRolesReorderedEvent) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

type RbacRoleAssignedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleAssignedEvent) Reset() {
	*x = RbacRoleAssignedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleAssignedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleAssignedEvent) ProtoMessage() {}

func (x *RbacRoleAssignedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleAssignedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleAssignedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{5}
}

func (x *RbacRoleAssignedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RbacRoleAssignedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RbacRoleRevokedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacRoleRevokedEvent) Reset() {
	*x = RbacRoleRevokedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacRoleRevokedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacRoleRevokedEvent) ProtoMessage() {}

func (x *RbacRoleRevokedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacRoleRevokedEvent.ProtoReflect.Descriptor instead.
func (*RbacRoleRevokedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{6}
}

func (x *RbacRoleRevokedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RbacRoleRevokedEvent) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RbacPermissionGrantedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // "server", room ID, or group ID.
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacPermissionGrantedEvent) Reset() {
	*x = RbacPermissionGrantedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacPermissionGrantedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacPermissionGrantedEvent) ProtoMessage() {}

func (x *RbacPermissionGrantedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacPermissionGrantedEvent.ProtoReflect.Descriptor instead.
func (*RbacPermissionGrantedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{7}
}

func (x *RbacPermissionGrantedEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RbacPermissionGrantedEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RbacPermissionGrantedEvent) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type RbacPermissionDeniedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // "server", room ID, or group ID.
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacPermissionDeniedEvent) Reset() {
	*x = RbacPermissionDeniedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacPermissionDeniedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacPermissionDeniedEvent) ProtoMessage() {}

func (x *RbacPermissionDeniedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacPermissionDeniedEvent.ProtoReflect.Descriptor instead.
func (*RbacPermissionDeniedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{8}
}

func (x *RbacPermissionDeniedEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RbacPermissionDeniedEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RbacPermissionDeniedEvent) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// Removes any explicit allow or deny, returning this permission to inherited/no-decision state.
type RbacPermissionClearedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // "server", room ID, or group ID.
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RbacPermissionClearedEvent) Reset() {
	*x = RbacPermissionClearedEvent{}
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RbacPermissionClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RbacPermissionClearedEvent) ProtoMessage() {}

func (x *RbacPermissionClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_rbac_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RbacPermissionClearedEvent.ProtoReflect.Descriptor instead.
func (*RbacPermissionClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_rbac_events_proto_rawDescGZIP(), []int{9}
}

func (x *RbacPermissionClearedEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RbacPermissionClearedEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RbacPermissionClearedEvent) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

var File_chatto_core_v1_rbac_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_rbac_events_proto_rawDesc = "" +
	"\n" +
	" chatto/core/v1/rbac_events.proto\x12\x0echatto.core.v1\"\x8c\x01\n" +
	"\x14RbacRoleCreatedEvent\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"a\n" +
	"\x1fRbacRoleDisplayNameChangedEvent\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"`\n" +
	"\x1fRbacRoleDescriptionChangedEvent\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"3\n" +
	"\x14RbacRoleDeletedEvent\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\"8\n" +
	"\x17RbacRolesReorderedEvent\x12\x1d\n" +
	"\n" +
	"role_names\x18\x01 \x03(\tR\troleNames\"M\n" +
	"\x15RbacRoleAssignedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"L\n" +
	"\x14RbacRoleRevokedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\"r\n" +
	"\x1aRbacPermissionGrantedEvent\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"q\n" +
	"\x19RbacPermissionDeniedEvent\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"r\n" +
	"\x1aRbacPermissionClearedEvent\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permissionB\xb2\x01\n" +
	"\x12com.chatto.core.v1B\x0fRbacEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_rbac_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_rbac_events_proto_rawDescData []byte
)

func file_chatto_core_v1_rbac_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_rbac_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_rbac_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_rbac_events_proto_rawDesc), len(file_chatto_core_v1_rbac_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_rbac_events_proto_rawDescData
}

var file_chatto_core_v1_rbac_events_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chatto_core_v1_rbac_events_proto_goTypes = []any{
	(*RbacRoleCreatedEvent)(nil),            // 0: chatto.core.v1.RbacRoleCreatedEvent
	(*RbacRoleDisplayNameChangedEvent)(nil), // 1: chatto.core.v1.RbacRoleDisplayNameChangedEvent
	(*RbacRoleDescriptionChangedEvent)(nil), // 2: chatto.core.v1.RbacRoleDescriptionChangedEvent
	(*RbacRoleDeletedEvent)(nil),            // 3: chatto.core.v1.RbacRoleDeletedEvent
	(*RbacRolesReorderedEvent)(nil),         // 4: chatto.core.v1.RbacRolesReorderedEvent
	(*RbacRoleAssignedEvent)(nil),           // 5: chatto.core.v1.RbacRoleAssignedEvent
	(*RbacRoleRevokedEvent)(nil),            // 6: chatto.core.v1.RbacRoleRevokedEvent
	(*RbacPermissionGrantedEvent)(nil),      // 7: chatto.core.v1.RbacPermissionGrantedEvent
	(*RbacPermissionDeniedEvent)(nil),       // 8: chatto.core.v1.RbacPermissionDeniedEvent
	(*RbacPermissionClearedEvent)(nil),      // 9: chatto.core.v1.RbacPermissionClearedEvent
}
var file_chatto_core_v1_rbac_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_rbac_events_proto_init() }
func file_chatto_core_v1_rbac_events_proto_init() {
	if File_chatto_core_v1_rbac_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_rbac_events_proto_rawDesc), len(file_chatto_core_v1_rbac_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_rbac_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_rbac_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_rbac_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_rbac_events_proto = out.File
	file_chatto_core_v1_rbac_events_proto_goTypes = nil
	file_chatto_core_v1_rbac_events_proto_depIdxs = nil
}
