// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/reaction_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionAddedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID - identifies the room containing the message
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the message being reacted to (NanoID)
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// The emoji used for the reaction (shortcode name)
	Emoji         string `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionAddedEvent) Reset() {
	*x = ReactionAddedEvent{}
	mi := &file_chatto_core_v1_reaction_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionAddedEvent) ProtoMessage() {}

func (x *ReactionAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_reaction_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionAddedEvent.ProtoReflect.Descriptor instead.
func (*ReactionAddedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_reaction_events_proto_rawDescGZIP(), []int{0}
}

func (x *ReactionAddedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReactionAddedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *ReactionAddedEvent) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type ReactionRemovedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID - identifies the room containing the message
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the message the reaction was removed from (NanoID)
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// The emoji shortcode that was removed
	Emoji         string `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionRemovedEvent) Reset() {
	*x = ReactionRemovedEvent{}
	mi := &file_chatto_core_v1_reaction_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionRemovedEvent) ProtoMessage() {}

func (x *ReactionRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_reaction_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionRemovedEvent.ProtoReflect.Descriptor instead.
func (*ReactionRemovedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_reaction_events_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionRemovedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReactionRemovedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *ReactionRemovedEvent) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

var File_chatto_core_v1_reaction_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_reaction_events_proto_rawDesc = "" +
	"\n" +
	"$chatto/core/v1/reaction_events.proto\x12\x0echatto.core.v1\"}\n" +
	"\x12ReactionAddedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emojiJ\x04\b\x01\x10\x02R\bspace_id\"\x7f\n" +
	"\x14ReactionRemovedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emojiJ\x04\b\x01\x10\x02R\bspace_idB\xb6\x01\n" +
	"\x12com.chatto.core.v1B\x13ReactionEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_reaction_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_reaction_events_proto_rawDescData []byte
)

func file_chatto_core_v1_reaction_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_reaction_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_reaction_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_reaction_events_proto_rawDesc), len(file_chatto_core_v1_reaction_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_reaction_events_proto_rawDescData
}

var file_chatto_core_v1_reaction_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_reaction_events_proto_goTypes = []any{
	(*ReactionAddedEvent)(nil),   // 0: chatto.core.v1.ReactionAddedEvent
	(*ReactionRemovedEvent)(nil), // 1: chatto.core.v1.ReactionRemovedEvent
}
var file_chatto_core_v1_reaction_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_reaction_events_proto_init() }
func file_chatto_core_v1_reaction_events_proto_init() {
	if File_chatto_core_v1_reaction_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_reaction_events_proto_rawDesc), len(file_chatto_core_v1_reaction_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_reaction_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_reaction_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_reaction_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_reaction_events_proto = out.File
	file_chatto_core_v1_reaction_events_proto_goTypes = nil
	file_chatto_core_v1_reaction_events_proto_depIdxs = nil
}
