// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/server_config_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "hmans.de/chatto/internal/pb/chatto/config/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Durable server-config event for the EVT log. Carries the
// complete ServerConfig snapshot after the change so projections and
// the audit log can reconstruct state without reaching back to KV.
// Distinct from the live-only ServerConfigUpdatedEvent at field 1000,
// which still rides the legacy live broadcast path during the
// migration window.
type ServerConfigChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete server config after the change.
	Config        *v1.ServerConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfigChangedEvent) Reset() {
	*x = ServerConfigChangedEvent{}
	mi := &file_chatto_core_v1_server_config_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfigChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfigChangedEvent) ProtoMessage() {}

func (x *ServerConfigChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_config_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfigChangedEvent.ProtoReflect.Descriptor instead.
func (*ServerConfigChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_config_events_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfigChangedEvent) GetConfig() *v1.ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Notifies clients that server configuration was updated.
// Clients should refetch server info to get the new values.
type ServerConfigUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated server name
	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// The updated MOTD (empty if cleared)
	Motd string `protobuf:"bytes,2,opt,name=motd,proto3" json:"motd,omitempty"`
	// The updated welcome message (empty if cleared)
	WelcomeMessage string `protobuf:"bytes,3,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	// The updated blocked usernames (newline-separated, empty if cleared)
	BlockedUsernames string `protobuf:"bytes,4,opt,name=blocked_usernames,json=blockedUsernames,proto3" json:"blocked_usernames,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerConfigUpdatedEvent) Reset() {
	*x = ServerConfigUpdatedEvent{}
	mi := &file_chatto_core_v1_server_config_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfigUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfigUpdatedEvent) ProtoMessage() {}

func (x *ServerConfigUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_server_config_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfigUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ServerConfigUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_server_config_events_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfigUpdatedEvent) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfigUpdatedEvent) GetMotd() string {
	if x != nil {
		return x.Motd
	}
	return ""
}

func (x *ServerConfigUpdatedEvent) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

func (x *ServerConfigUpdatedEvent) GetBlockedUsernames() string {
	if x != nil {
		return x.BlockedUsernames
	}
	return ""
}

var File_chatto_core_v1_server_config_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_server_config_events_proto_rawDesc = "" +
	"\n" +
	")chatto/core/v1/server_config_events.proto\x12\x0echatto.core.v1\x1a\x1dchatto/config/v1/config.proto\"R\n" +
	"\x18ServerConfigChangedEvent\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1e.chatto.config.v1.ServerConfigR\x06config\"\xa5\x01\n" +
	"\x18ServerConfigUpdatedEvent\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04motd\x18\x02 \x01(\tR\x04motd\x12'\n" +
	"\x0fwelcome_message\x18\x03 \x01(\tR\x0ewelcomeMessage\x12+\n" +
	"\x11blocked_usernames\x18\x04 \x01(\tR\x10blockedUsernamesB\xba\x01\n" +
	"\x12com.chatto.core.v1B\x17ServerConfigEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_server_config_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_server_config_events_proto_rawDescData []byte
)

func file_chatto_core_v1_server_config_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_server_config_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_server_config_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_server_config_events_proto_rawDesc), len(file_chatto_core_v1_server_config_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_server_config_events_proto_rawDescData
}

var file_chatto_core_v1_server_config_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_server_config_events_proto_goTypes = []any{
	(*ServerConfigChangedEvent)(nil), // 0: chatto.core.v1.ServerConfigChangedEvent
	(*ServerConfigUpdatedEvent)(nil), // 1: chatto.core.v1.ServerConfigUpdatedEvent
	(*v1.ServerConfig)(nil),          // 2: chatto.config.v1.ServerConfig
}
var file_chatto_core_v1_server_config_events_proto_depIdxs = []int32{
	2, // 0: chatto.core.v1.ServerConfigChangedEvent.config:type_name -> chatto.config.v1.ServerConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_server_config_events_proto_init() }
func file_chatto_core_v1_server_config_events_proto_init() {
	if File_chatto_core_v1_server_config_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_server_config_events_proto_rawDesc), len(file_chatto_core_v1_server_config_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_server_config_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_server_config_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_server_config_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_server_config_events_proto = out.File
	file_chatto_core_v1_server_config_events_proto_goTypes = nil
	file_chatto_core_v1_server_config_events_proto_depIdxs = nil
}
