// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/messages.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MessageServiceName is the fully-qualified name of the MessageService service.
	MessageServiceName = "chatto.api.v1.MessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MessageServicePostMessageProcedure is the fully-qualified name of the MessageService's
	// PostMessage RPC.
	MessageServicePostMessageProcedure = "/chatto.api.v1.MessageService/PostMessage"
)

// MessageServiceClient is a client for the chatto.api.v1.MessageService service.
type MessageServiceClient interface {
	// Posts a message for the current user. The user must be a room member and
	// must have message.post for room messages or message.post-in-thread for
	// thread replies. Echoing a thread reply also requires message.echo and
	// message.post.
	PostMessage(context.Context, *connect.Request[v1.PostMessageRequest]) (*connect.Response[v1.PostMessageResponse], error)
}

// NewMessageServiceClient constructs a client for the chatto.api.v1.MessageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	messageServiceMethods := v1.File_chatto_api_v1_messages_proto.Services().ByName("MessageService").Methods()
	return &messageServiceClient{
		postMessage: connect.NewClient[v1.PostMessageRequest, v1.PostMessageResponse](
			httpClient,
			baseURL+MessageServicePostMessageProcedure,
			connect.WithSchema(messageServiceMethods.ByName("PostMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// messageServiceClient implements MessageServiceClient.
type messageServiceClient struct {
	postMessage *connect.Client[v1.PostMessageRequest, v1.PostMessageResponse]
}

// PostMessage calls chatto.api.v1.MessageService.PostMessage.
func (c *messageServiceClient) PostMessage(ctx context.Context, req *connect.Request[v1.PostMessageRequest]) (*connect.Response[v1.PostMessageResponse], error) {
	return c.postMessage.CallUnary(ctx, req)
}

// MessageServiceHandler is an implementation of the chatto.api.v1.MessageService service.
type MessageServiceHandler interface {
	// Posts a message for the current user. The user must be a room member and
	// must have message.post for room messages or message.post-in-thread for
	// thread replies. Echoing a thread reply also requires message.echo and
	// message.post.
	PostMessage(context.Context, *connect.Request[v1.PostMessageRequest]) (*connect.Response[v1.PostMessageResponse], error)
}

// NewMessageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMessageServiceHandler(svc MessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	messageServiceMethods := v1.File_chatto_api_v1_messages_proto.Services().ByName("MessageService").Methods()
	messageServicePostMessageHandler := connect.NewUnaryHandler(
		MessageServicePostMessageProcedure,
		svc.PostMessage,
		connect.WithSchema(messageServiceMethods.ByName("PostMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.MessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MessageServicePostMessageProcedure:
			messageServicePostMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMessageServiceHandler struct{}

func (UnimplementedMessageServiceHandler) PostMessage(context.Context, *connect.Request[v1.PostMessageRequest]) (*connect.Response[v1.PostMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.MessageService.PostMessage is not implemented"))
}
