// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/operator/v1/users.proto

package operatorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/operator/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OperatorUserServiceName is the fully-qualified name of the OperatorUserService service.
	OperatorUserServiceName = "chatto.operator.v1.OperatorUserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OperatorUserServiceCreateUserProcedure is the fully-qualified name of the OperatorUserService's
	// CreateUser RPC.
	OperatorUserServiceCreateUserProcedure = "/chatto.operator.v1.OperatorUserService/CreateUser"
	// OperatorUserServiceListUsersProcedure is the fully-qualified name of the OperatorUserService's
	// ListUsers RPC.
	OperatorUserServiceListUsersProcedure = "/chatto.operator.v1.OperatorUserService/ListUsers"
	// OperatorUserServiceGetUserProcedure is the fully-qualified name of the OperatorUserService's
	// GetUser RPC.
	OperatorUserServiceGetUserProcedure = "/chatto.operator.v1.OperatorUserService/GetUser"
	// OperatorUserServiceAssignRoleProcedure is the fully-qualified name of the OperatorUserService's
	// AssignRole RPC.
	OperatorUserServiceAssignRoleProcedure = "/chatto.operator.v1.OperatorUserService/AssignRole"
	// OperatorUserServiceRevokeRoleProcedure is the fully-qualified name of the OperatorUserService's
	// RevokeRole RPC.
	OperatorUserServiceRevokeRoleProcedure = "/chatto.operator.v1.OperatorUserService/RevokeRole"
	// OperatorUserServiceUpdateUserProcedure is the fully-qualified name of the OperatorUserService's
	// UpdateUser RPC.
	OperatorUserServiceUpdateUserProcedure = "/chatto.operator.v1.OperatorUserService/UpdateUser"
	// OperatorUserServiceSetUserPasswordProcedure is the fully-qualified name of the
	// OperatorUserService's SetUserPassword RPC.
	OperatorUserServiceSetUserPasswordProcedure = "/chatto.operator.v1.OperatorUserService/SetUserPassword"
	// OperatorUserServiceDeleteUserProcedure is the fully-qualified name of the OperatorUserService's
	// DeleteUser RPC.
	OperatorUserServiceDeleteUserProcedure = "/chatto.operator.v1.OperatorUserService/DeleteUser"
	// OperatorUserServiceAddVerifiedEmailProcedure is the fully-qualified name of the
	// OperatorUserService's AddVerifiedEmail RPC.
	OperatorUserServiceAddVerifiedEmailProcedure = "/chatto.operator.v1.OperatorUserService/AddVerifiedEmail"
	// OperatorUserServiceClearUsernameCooldownProcedure is the fully-qualified name of the
	// OperatorUserService's ClearUsernameCooldown RPC.
	OperatorUserServiceClearUsernameCooldownProcedure = "/chatto.operator.v1.OperatorUserService/ClearUsernameCooldown"
)

// OperatorUserServiceClient is a client for the chatto.operator.v1.OperatorUserService service.
type OperatorUserServiceClient interface {
	// Creates a user as a local operator.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// Lists users for operator inspection.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// Gets one user plus role/permission metadata for operator inspection.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// Assigns a role to a user.
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	// Revokes a role from a user.
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	// Updates a user's login and/or display name as an operator action.
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	// Sets a user's password as a local operator.
	SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error)
	// Permanently deletes a user account.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// Adds an already-verified email address to a user.
	AddVerifiedEmail(context.Context, *connect.Request[v1.AddVerifiedEmailRequest]) (*connect.Response[v1.AddVerifiedEmailResponse], error)
	// Clears a user's self-service username-change cooldown.
	ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error)
}

// NewOperatorUserServiceClient constructs a client for the chatto.operator.v1.OperatorUserService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOperatorUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OperatorUserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	operatorUserServiceMethods := v1.File_chatto_operator_v1_users_proto.Services().ByName("OperatorUserService").Methods()
	return &operatorUserServiceClient{
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+OperatorUserServiceCreateUserProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+OperatorUserServiceListUsersProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+OperatorUserServiceGetUserProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		assignRole: connect.NewClient[v1.AssignRoleRequest, v1.AssignRoleResponse](
			httpClient,
			baseURL+OperatorUserServiceAssignRoleProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		revokeRole: connect.NewClient[v1.RevokeRoleRequest, v1.RevokeRoleResponse](
			httpClient,
			baseURL+OperatorUserServiceRevokeRoleProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("RevokeRole")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+OperatorUserServiceUpdateUserProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		setUserPassword: connect.NewClient[v1.SetUserPasswordRequest, v1.SetUserPasswordResponse](
			httpClient,
			baseURL+OperatorUserServiceSetUserPasswordProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("SetUserPassword")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+OperatorUserServiceDeleteUserProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		addVerifiedEmail: connect.NewClient[v1.AddVerifiedEmailRequest, v1.AddVerifiedEmailResponse](
			httpClient,
			baseURL+OperatorUserServiceAddVerifiedEmailProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("AddVerifiedEmail")),
			connect.WithClientOptions(opts...),
		),
		clearUsernameCooldown: connect.NewClient[v1.ClearUsernameCooldownRequest, v1.ClearUsernameCooldownResponse](
			httpClient,
			baseURL+OperatorUserServiceClearUsernameCooldownProcedure,
			connect.WithSchema(operatorUserServiceMethods.ByName("ClearUsernameCooldown")),
			connect.WithClientOptions(opts...),
		),
	}
}

// operatorUserServiceClient implements OperatorUserServiceClient.
type operatorUserServiceClient struct {
	createUser            *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	listUsers             *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	getUser               *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	assignRole            *connect.Client[v1.AssignRoleRequest, v1.AssignRoleResponse]
	revokeRole            *connect.Client[v1.RevokeRoleRequest, v1.RevokeRoleResponse]
	updateUser            *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	setUserPassword       *connect.Client[v1.SetUserPasswordRequest, v1.SetUserPasswordResponse]
	deleteUser            *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	addVerifiedEmail      *connect.Client[v1.AddVerifiedEmailRequest, v1.AddVerifiedEmailResponse]
	clearUsernameCooldown *connect.Client[v1.ClearUsernameCooldownRequest, v1.ClearUsernameCooldownResponse]
}

// CreateUser calls chatto.operator.v1.OperatorUserService.CreateUser.
func (c *operatorUserServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// ListUsers calls chatto.operator.v1.OperatorUserService.ListUsers.
func (c *operatorUserServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls chatto.operator.v1.OperatorUserService.GetUser.
func (c *operatorUserServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// AssignRole calls chatto.operator.v1.OperatorUserService.AssignRole.
func (c *operatorUserServiceClient) AssignRole(ctx context.Context, req *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// RevokeRole calls chatto.operator.v1.OperatorUserService.RevokeRole.
func (c *operatorUserServiceClient) RevokeRole(ctx context.Context, req *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return c.revokeRole.CallUnary(ctx, req)
}

// UpdateUser calls chatto.operator.v1.OperatorUserService.UpdateUser.
func (c *operatorUserServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// SetUserPassword calls chatto.operator.v1.OperatorUserService.SetUserPassword.
func (c *operatorUserServiceClient) SetUserPassword(ctx context.Context, req *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error) {
	return c.setUserPassword.CallUnary(ctx, req)
}

// DeleteUser calls chatto.operator.v1.OperatorUserService.DeleteUser.
func (c *operatorUserServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// AddVerifiedEmail calls chatto.operator.v1.OperatorUserService.AddVerifiedEmail.
func (c *operatorUserServiceClient) AddVerifiedEmail(ctx context.Context, req *connect.Request[v1.AddVerifiedEmailRequest]) (*connect.Response[v1.AddVerifiedEmailResponse], error) {
	return c.addVerifiedEmail.CallUnary(ctx, req)
}

// ClearUsernameCooldown calls chatto.operator.v1.OperatorUserService.ClearUsernameCooldown.
func (c *operatorUserServiceClient) ClearUsernameCooldown(ctx context.Context, req *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error) {
	return c.clearUsernameCooldown.CallUnary(ctx, req)
}

// OperatorUserServiceHandler is an implementation of the chatto.operator.v1.OperatorUserService
// service.
type OperatorUserServiceHandler interface {
	// Creates a user as a local operator.
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	// Lists users for operator inspection.
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// Gets one user plus role/permission metadata for operator inspection.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// Assigns a role to a user.
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	// Revokes a role from a user.
	RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error)
	// Updates a user's login and/or display name as an operator action.
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	// Sets a user's password as a local operator.
	SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error)
	// Permanently deletes a user account.
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error)
	// Adds an already-verified email address to a user.
	AddVerifiedEmail(context.Context, *connect.Request[v1.AddVerifiedEmailRequest]) (*connect.Response[v1.AddVerifiedEmailResponse], error)
	// Clears a user's self-service username-change cooldown.
	ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error)
}

// NewOperatorUserServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOperatorUserServiceHandler(svc OperatorUserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	operatorUserServiceMethods := v1.File_chatto_operator_v1_users_proto.Services().ByName("OperatorUserService").Methods()
	operatorUserServiceCreateUserHandler := connect.NewUnaryHandler(
		OperatorUserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(operatorUserServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceListUsersHandler := connect.NewUnaryHandler(
		OperatorUserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(operatorUserServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceGetUserHandler := connect.NewUnaryHandler(
		OperatorUserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(operatorUserServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceAssignRoleHandler := connect.NewUnaryHandler(
		OperatorUserServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(operatorUserServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceRevokeRoleHandler := connect.NewUnaryHandler(
		OperatorUserServiceRevokeRoleProcedure,
		svc.RevokeRole,
		connect.WithSchema(operatorUserServiceMethods.ByName("RevokeRole")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceUpdateUserHandler := connect.NewUnaryHandler(
		OperatorUserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(operatorUserServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceSetUserPasswordHandler := connect.NewUnaryHandler(
		OperatorUserServiceSetUserPasswordProcedure,
		svc.SetUserPassword,
		connect.WithSchema(operatorUserServiceMethods.ByName("SetUserPassword")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceDeleteUserHandler := connect.NewUnaryHandler(
		OperatorUserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(operatorUserServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceAddVerifiedEmailHandler := connect.NewUnaryHandler(
		OperatorUserServiceAddVerifiedEmailProcedure,
		svc.AddVerifiedEmail,
		connect.WithSchema(operatorUserServiceMethods.ByName("AddVerifiedEmail")),
		connect.WithHandlerOptions(opts...),
	)
	operatorUserServiceClearUsernameCooldownHandler := connect.NewUnaryHandler(
		OperatorUserServiceClearUsernameCooldownProcedure,
		svc.ClearUsernameCooldown,
		connect.WithSchema(operatorUserServiceMethods.ByName("ClearUsernameCooldown")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.operator.v1.OperatorUserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OperatorUserServiceCreateUserProcedure:
			operatorUserServiceCreateUserHandler.ServeHTTP(w, r)
		case OperatorUserServiceListUsersProcedure:
			operatorUserServiceListUsersHandler.ServeHTTP(w, r)
		case OperatorUserServiceGetUserProcedure:
			operatorUserServiceGetUserHandler.ServeHTTP(w, r)
		case OperatorUserServiceAssignRoleProcedure:
			operatorUserServiceAssignRoleHandler.ServeHTTP(w, r)
		case OperatorUserServiceRevokeRoleProcedure:
			operatorUserServiceRevokeRoleHandler.ServeHTTP(w, r)
		case OperatorUserServiceUpdateUserProcedure:
			operatorUserServiceUpdateUserHandler.ServeHTTP(w, r)
		case OperatorUserServiceSetUserPasswordProcedure:
			operatorUserServiceSetUserPasswordHandler.ServeHTTP(w, r)
		case OperatorUserServiceDeleteUserProcedure:
			operatorUserServiceDeleteUserHandler.ServeHTTP(w, r)
		case OperatorUserServiceAddVerifiedEmailProcedure:
			operatorUserServiceAddVerifiedEmailHandler.ServeHTTP(w, r)
		case OperatorUserServiceClearUsernameCooldownProcedure:
			operatorUserServiceClearUsernameCooldownHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOperatorUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOperatorUserServiceHandler struct{}

func (UnimplementedOperatorUserServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.CreateUser is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.ListUsers is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.GetUser is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.AssignRole is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) RevokeRole(context.Context, *connect.Request[v1.RevokeRoleRequest]) (*connect.Response[v1.RevokeRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.RevokeRole is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.UpdateUser is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) SetUserPassword(context.Context, *connect.Request[v1.SetUserPasswordRequest]) (*connect.Response[v1.SetUserPasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.SetUserPassword is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserRequest]) (*connect.Response[v1.DeleteUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.DeleteUser is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) AddVerifiedEmail(context.Context, *connect.Request[v1.AddVerifiedEmailRequest]) (*connect.Response[v1.AddVerifiedEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.AddVerifiedEmail is not implemented"))
}

func (UnimplementedOperatorUserServiceHandler) ClearUsernameCooldown(context.Context, *connect.Request[v1.ClearUsernameCooldownRequest]) (*connect.Response[v1.ClearUsernameCooldownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.operator.v1.OperatorUserService.ClearUsernameCooldown is not implemented"))
}
